jobs:
  include:
    - stage: feature-test
      name: "Feature Test"
      os: linux
      dist: bionic
      language: php
      php: 7.4
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
        - composer self-update
        - composer install --optimize-autoloader --no-interaction
      script:
        - ./vendor/bin/phpunit
    - stage: install-test-72
      name: "Test in PHP 7.2"
      os: linux
      dist: xenial
      language: php
      php: 7.2
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - rm -rf ./composer-test/test-72
        - mkdir -p ./composer-test/test-72 && cd ./composer-test/test-72
        - composer init --no-interaction
        - composer require cixware/esewa-php-sdk
    - stage: install-test-73
      name: "Test in PHP 7.3"
      os: linux
      dist: xenial
      language: php
      php: 7.3
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - rm -rf ./composer-test/test-73
        - mkdir -p ./composer-test/test-73 && cd ./composer-test/test-73
        - composer init --no-interaction
        - composer require cixware/esewa-php-sdk
    - stage: install-test-74
      name: "Test in PHP 7.4"
      os: linux
      dist: bionic
      language: php
      php: 7.4
      before_script:
        - php --version
        - phpenv config-rm xdebug.ini
      script:
        - composer self-update
        - rm -rf ./composer-test/test-74
        - mkdir -p ./composer-test/test-74 && cd ./composer-test/test-74
        - composer init --no-interaction
        - composer require cixware/esewa-php-sdk
    - stage: install-test-nightly
      name: "Test in PHP nightly"
      os: linux
      dist: bionic
      language: php
      php: nightly
      before_script:
        - php --version
      script:
        - composer self-update
        - rm -rf ./composer-test/test-nightly
        - mkdir -p ./composer-test/test-nightly && cd ./composer-test/test-nightly
        - composer init --no-interaction
        - composer require cixware/esewa-php-sdk

branches:
  only:
    - master
    - develop
    - test

notifications:
  email:
    on_success: always
    on_failure: always
