name: Install

# run on
on:
  release:
    types: [created]
    branches: [main]

jobs:
  Test:
    # Current OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # OS list
        os: [ubuntu-latest]
        # Supported PHP versions
        php: ['7.4', '8.0', '8.1', '8.2']
    steps:
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: "Display version information"
        run: php --version && composer --version

      - name: "Initialize composer"
        run: composer init --no-interaction --stability=stable

      - name: "Install dependencies"
        run: composer require cixware/esewa-php-sdk
